// Single source of truth for all Vitreen products.
// Used by: Nav dropdown, /products index, /products/[slug] landing pages,
// and Solutions cross-referencing.

export type Category = 'viewing-rooms' | 'public-face' | 'operations' | 'institutional'

export const CATEGORIES: { id: Category; labelFr: string; labelEn: string; descFr: string; descEn: string }[] = [
  { id: 'viewing-rooms', labelFr: 'Viewing Rooms',  labelEn: 'Viewing Rooms',
    descFr: 'Cinq surfaces pour composer une salle privée et l’envoyer à un collectionneur.',
    descEn: 'Five surfaces for composing a private room and sending it to a collector.' },
  { id: 'public-face',   labelFr: 'Vitrine publique', labelEn: 'Public face',
    descFr: 'Le visage en ligne de votre galerie, vu par tous.',
    descEn: 'The online face of your gallery, seen by everyone.' },
  { id: 'operations',    labelFr: 'Opérations',     labelEn: 'Operations',
    descFr: 'Les outils internes : inventaire, ventes, relations, communication.',
    descEn: 'Internal tools: inventory, sales, relationships, communications.' },
  { id: 'institutional', labelFr: 'Institutionnel', labelEn: 'Institutional',
    descFr: 'Foires, consignations, prêts — la galerie comme institution.',
    descEn: 'Fairs, consignments, loans — the gallery as an institution.' },
]

export type Product = {
  slug: string
  name: string
  tag: string
  category: Category
  comingSoon?: boolean
  // Copy
  shortFr: string;     shortEn: string
  heroFr: string;      heroEn: string
  pitchFr: string;     pitchEn: string
  forWhoFr: string;    forWhoEn: string
  beforeFr: string;    beforeEn: string
  duringFr: string;    duringEn: string
  afterFr: string;     afterEn: string
  whyFr: string;       whyEn: string
  highlightFr: string[]; highlightEn: string[]
  // Visuals
  swatchBg: string
  swatchFg: string
  swatchSerif?: boolean
}

export const PRODUCTS: Product[] = [
  // ─────────── VIEWING ROOMS (5 working demos) ───────────
  {
    slug: 'canvas', name: 'Canvas', tag: 'Direct manipulation', category: 'viewing-rooms',
    shortFr: 'L’éditeur EST la viewing room. Tout est éditable en place.',
    shortEn: 'The editor IS the viewing room. Everything edits in place.',
    heroFr: 'Composez la viewing room comme un objet, pas comme un formulaire.',
    heroEn: 'Compose the viewing room as an object, not a form.',
    pitchFr: 'Pas de panneau d’édition. Pas d’aperçu séparé. Vous voyez exactement ce que le collectionneur recevra, et chaque mot, chaque image se modifie d’un clic. Le geste artisanal, à l’échelle du numérique.',
    pitchEn: 'No editing panel. No separate preview. You see exactly what the collector will receive — and every word, every image edits with a click. Hand-craft, at digital scale.',
    forWhoFr: 'Galeries qui composent par instinct et par goût.',
    forWhoEn: 'Galleries who compose by instinct and taste.',
    beforeFr: 'Vous arrivez sur une room déjà mise en page, peuplée d’un exemple réaliste.',
    beforeEn: 'You land on a fully composed sample room.',
    duringFr: 'Cliquez un titre pour l’écrire. Glissez une image, elle se place. Le destinataire reste épinglé en haut.',
    duringEn: 'Click a title to write it. Drop an image, it places itself. The recipient stays pinned at the top.',
    afterFr: 'Un seul bouton Envoyer. Confirmation. Envoyé.',
    afterEn: 'A single Send button. Confirm. Sent.',
    whyFr: 'Élimine la séparation entre éditer et voir.',
    whyEn: 'Eliminates the editor / preview split.',
    highlightFr: ['Édition contextuelle inline', 'Aperçu = artefact final', 'Glisser-déposer libre'],
    highlightEn: ['Inline contextual editing', 'Preview = final artefact', 'Free drag-and-drop'],
    swatchBg: '#FAF6EE', swatchFg: '#1C1814', swatchSerif: true,
  },
  {
    slug: 'desk', name: 'Desk', tag: 'Operator mode', category: 'viewing-rooms',
    shortFr: 'Pour les galeries qui envoient 20+ viewing rooms par mois.',
    shortEn: 'For galleries sending 20+ viewing rooms a month.',
    heroFr: 'La viewing room comme pipeline de vente, pas comme événement.',
    heroEn: 'The viewing room as a sales pipeline, not a one-off event.',
    pitchFr: 'Une table dense à la Linear. Statuts (Brouillon, Envoyée, Ouverte, Répondue, Vendue), recherche en Cmd+K, raccourcis clavier, composition inline. Pour les galeries qui font de la viewing room un canal commercial sérieux.',
    pitchEn: 'A dense Linear-grade table. Status badges (Draft, Sent, Opened, Replied, Sold), Cmd+K search, keyboard shortcuts, inline composition. For galleries who treat viewing rooms as a real sales channel.',
    forWhoFr: 'Galeries moyennes et grandes qui suivent leurs envois comme un pipeline.',
    forWhoEn: 'Mid-size and large galleries who treat sending as a pipeline.',
    beforeFr: 'Vue d’ensemble de toutes les viewing rooms. Filtrer par statut. Cmd+K pour chercher.',
    beforeEn: 'Overview of every viewing room. Filter by status. Cmd+K to search.',
    duringFr: 'Cliquer une ligne pour la déplier inline et éditer. Sans changer de page.',
    duringEn: 'Click a row to expand inline and edit. No context switch.',
    afterFr: 'Bouton Envoyer par ligne. Le statut suit le cycle de vie automatiquement.',
    afterEn: 'Send button per row. Status auto-tracks the lifecycle.',
    whyFr: 'Optimisé pour la vitesse et le suivi à grande échelle.',
    whyEn: 'Optimised for speed and tracking at scale.',
    highlightFr: ['Cmd+K palette de commandes', 'Statuts de cycle de vente', 'Composition inline dans la table'],
    highlightEn: ['Cmd+K command palette', 'Sales-cycle status tracking', 'Inline composition'],
    swatchBg: '#FAFAFA', swatchFg: '#0A0A0A',
  },
  {
    slug: 'pocket', name: 'Pocket', tag: 'Compose where they read', category: 'viewing-rooms',
    shortFr: 'Composez sur un iPhone, parce que c’est là qu’ils ouvriront.',
    shortEn: 'Compose on an iPhone — that’s where they’ll open it.',
    heroFr: '87 % des viewing rooms sont ouvertes sur mobile. Composez là où on les lit.',
    heroEn: '87% of viewing rooms open on mobile. Compose where they’re read.',
    pitchFr: 'Le bureau affiche un véritable iPhone au centre. Vos modifications s’appliquent en direct dans la maquette du téléphone. Un compteur de caractères vous prévient quand un titre déborde sur mobile. Vous concevez pour le périphérique réel.',
    pitchEn: 'The desktop shows a real iPhone at the centre. Edits apply live inside the phone mockup. A character counter warns when titles overflow on mobile. You design for the actual device.',
    forWhoFr: 'Galeries qui assument que leurs collectionneurs lisent entre deux rendez-vous.',
    forWhoEn: 'Galleries who accept their collectors read between meetings.',
    beforeFr: 'Cadre desktop avec iPhone centré, déjà rempli d’un exemple.',
    beforeEn: 'Desktop frame, centered iPhone, already populated.',
    duringFr: 'Sélectionnez une section. Éditez à droite. La maquette téléphone s’anime en direct.',
    duringEn: 'Pick a section. Edit on the right. The phone preview animates live.',
    afterFr: 'Bouton d’envoi. Livraison par e-mail, ouverture sur leur téléphone exactement comme composée.',
    afterEn: 'Send. Delivers via email, opens on their phone exactly as composed.',
    whyFr: 'Aligne la surface de composition avec la surface de consommation.',
    whyEn: 'Aligns the composing surface with the reading surface.',
    highlightFr: ['Aperçu iPhone en direct', 'Compteurs de débordement', 'Édition par section'],
    highlightEn: ['Live iPhone preview', 'Overflow counters', 'Section-by-section editing'],
    swatchBg: '#1B1A18', swatchFg: '#F5C557',
  },
  {
    slug: 'proof', name: 'Proof', tag: 'Print catalogue', category: 'viewing-rooms',
    shortFr: 'Une viewing room comme un catalogue d’art imprimé.',
    shortEn: 'A viewing room as a printed art catalogue.',
    heroFr: 'Le catalogue de luxe, dans la sobriété d’une épreuve d’imprimerie.',
    heroEn: 'The luxury catalogue, in the restraint of a press proof.',
    pitchFr: 'L’éditeur prend la forme d’une épreuve d’offset : marques de coupe, grain papier, typographie classique. Couverture, lettre, planches, colophon. Sortie double : un PDF prêt-à-presse et un lien numérique privé.',
    pitchEn: 'The editor takes the shape of an offset proof: crop marks, paper grain, classical typography. Cover, letter, plates, colophon. Two outputs: a press-ready PDF and a private digital link.',
    forWhoFr: 'Galeries qui impriment encore, signent leurs e-mails, soignent l’objet matériel.',
    forWhoEn: 'Galleries that still print, sign their emails, care about the material object.',
    beforeFr: 'Maquette 6 pages : couverture, lettre, 3 planches, colophon. Marques de coupe visibles.',
    beforeEn: 'Sample 6-page mockup: cover, letter, 3 plates, colophon. Crop marks visible.',
    duringFr: 'Cliquer pour éditer n’importe quel mot. Naviguer les planches. Ajouter, retirer.',
    duringEn: 'Click any text to edit. Navigate plates. Add, remove.',
    afterFr: 'Export PDF prêt-presse ou lien numérique privé. Le collectionneur reçoit les deux.',
    afterEn: 'Press-ready PDF or private digital link. The collector receives both.',
    whyFr: 'Signal de soin matériel pour les galeries dont le goût se voit avant la transaction.',
    whyEn: 'A material-craft signal for galleries whose taste shows before the transaction.',
    highlightFr: ['Marques de coupe et grain papier', 'Export PDF prêt-presse', 'Composition par planche'],
    highlightEn: ['Crop marks and paper grain', 'Press-ready PDF export', 'Plate-by-plate composition'],
    swatchBg: '#15110D', swatchFg: '#D4A04C', swatchSerif: true,
  },
  {
    slug: 'studio', name: 'Studio', tag: 'Voice-led narration', category: 'viewing-rooms',
    shortFr: 'Pas de saisie. Vous racontez chaque œuvre, comme en personne.',
    shortEn: 'No typing. You narrate each work — like in person.',
    heroFr: 'Le studio visit, à distance. Votre voix sur chaque œuvre.',
    heroEn: 'The studio visit, at a distance. Your voice on every work.',
    pitchFr: 'Plus de formulaire. La galerie enregistre une narration audio sur chaque œuvre — 30 à 90 secondes, le ton de la visite d’atelier. Le collectionneur écoute en regardant l’image, sur son téléphone. Personnel. Inimitable.',
    pitchEn: 'No form. The gallery records audio narration over each work — 30 to 90 seconds, the tone of a studio visit. The collector listens while viewing the image, on their phone. Personal. Unforgeable.',
    forWhoFr: 'Galeristes qui sont brillants en personne et veulent passer à l’échelle.',
    forWhoEn: 'Gallerists who are great in person and want to scale that.',
    beforeFr: 'Stage d’enregistrement avec œuvre active en hero. Liste de pistes à droite.',
    beforeEn: 'Recording stage, active artwork as hero. Track list on the right.',
    duringFr: 'Bouton rouge d’enregistrement. Forme d’ondes en direct. Passer à la piste suivante.',
    duringEn: 'Red record button. Live waveform. Move to the next track.',
    afterFr: 'Quand toutes les pistes sont enregistrées, envoyer. Hybride image + audio.',
    afterEn: 'When all tracks recorded, send. Hybrid image + audio.',
    whyFr: 'Met votre voix au centre de la relation. Inimitable.',
    whyEn: 'Puts your voice at the centre of the relationship. Unforgeable.',
    highlightFr: ['Enregistrement par œuvre', 'Forme d’ondes en direct', 'Lecture image + audio'],
    highlightEn: ['Per-artwork recording', 'Live waveform', 'Image + audio playback'],
    swatchBg: '#0A0A0B', swatchFg: '#F43F5E',
  },

  // ─────────── PUBLIC FACE (3 new) ───────────
  {
    slug: 'sites', name: 'Sites', tag: 'Public gallery website', category: 'public-face', comingSoon: true,
    shortFr: 'Le site public de votre galerie : artistes, expositions, contact.',
    shortEn: 'Your gallery’s public website: artists, exhibitions, contact.',
    heroFr: 'Un site qui parle d’art, pas de SaaS.',
    heroEn: 'A website that speaks of art, not SaaS.',
    pitchFr: 'Templates pensés pour les galeries d’art contemporain. Pages artistes, archives d’expositions, calendrier, vues d’installation, presse, contact. Hébergé, sécurisé, mis à jour par vous sans intermédiaire.',
    pitchEn: 'Templates built for contemporary art galleries. Artist pages, exhibition archives, calendar, installation views, press, contact. Hosted, secure, updated by you without an intermediary.',
    forWhoFr: 'Toute galerie qui veut exister en ligne sans dépendre d’un développeur.',
    forWhoEn: 'Any gallery that wants an online presence without depending on a developer.',
    beforeFr: 'Choisissez un template parmi cinq, fait pour la photographie, la peinture, la sculpture, le contemporain.',
    beforeEn: 'Pick one of five templates, made for photography, painting, sculpture, contemporary.',
    duringFr: 'Composez les pages comme dans Canvas — clic, édition inline. Tout en français et anglais.',
    duringEn: 'Compose pages like in Canvas — click, edit inline. Everything in French and English.',
    afterFr: 'Publication un domaine. SSL, sauvegardes, performance auto.',
    afterEn: 'Publish to a domain. SSL, backups, performance auto.',
    whyFr: 'Le visage en ligne de votre galerie, sans le poids d’un Wordpress sur-customisé.',
    whyEn: 'The online face of your gallery, without the weight of an over-customised Wordpress.',
    highlightFr: ['Templates dédiés galeries', 'Bilingue FR/EN par défaut', 'Hébergé, SSL, sauvegardes'],
    highlightEn: ['Gallery-dedicated templates', 'Bilingual FR/EN by default', 'Hosted, SSL, backups'],
    swatchBg: '#F2EBDF', swatchFg: '#A04A2E', swatchSerif: true,
  },
  {
    slug: 'roster', name: 'Roster', tag: 'Artist programme', category: 'public-face', comingSoon: true,
    shortFr: 'La programmation artistique : portfolios, biographies, CVs d’exposition.',
    shortEn: 'The artist programme: portfolios, biographies, exhibition CVs.',
    heroFr: 'La programmation, vue depuis l’intérieur et depuis le public.',
    heroEn: 'The programme, seen from inside and from the public.',
    pitchFr: 'Chaque artiste reçoit sa page : œuvres récentes, série en cours, CV d’exposition, presse, vidéos d’atelier. Édité par la galerie, partageable avec curateurs et institutions, intégré au site Sites.',
    pitchEn: 'Each artist gets a page: recent works, current series, exhibition CV, press, studio videos. Edited by the gallery, shareable with curators and institutions, integrated with Sites.',
    forWhoFr: 'Galeries qui représentent un programme stable d’artistes.',
    forWhoEn: 'Galleries representing a stable artist programme.',
    beforeFr: 'Liste d’artistes du programme, classés par génération ou rotation.',
    beforeEn: 'Artist list, sorted by generation or rotation.',
    duringFr: 'Une fiche par artiste : bio, série, presse. Versions publique et interne.',
    duringEn: 'One sheet per artist: bio, series, press. Public and internal versions.',
    afterFr: 'Lien partageable avec un commissaire ou une foire d’art.',
    afterEn: 'Shareable link for a curator or art fair.',
    whyFr: 'Centralise tout ce qu’on doit dire sur un artiste, en un seul endroit éditable.',
    whyEn: 'Centralises everything to say about an artist, in one editable place.',
    highlightFr: ['Fiche artiste publique + interne', 'CV d’expositions structuré', 'Presse, vidéos, séries'],
    highlightEn: ['Public + internal artist sheet', 'Structured exhibition CV', 'Press, videos, series'],
    swatchBg: '#1F2C24', swatchFg: '#E4DCC2', swatchSerif: true,
  },
  {
    slug: 'archive', name: 'Archive', tag: 'Exhibition history', category: 'public-face', comingSoon: true,
    shortFr: 'L’histoire vivante de vos expositions passées.',
    shortEn: 'The living history of your past exhibitions.',
    heroFr: 'Ce que vous avez montré construit ce que vous montrerez.',
    heroEn: 'What you have shown builds what you will show.',
    pitchFr: 'Chaque exposition reçoit sa page : vues d’installation, liste d’œuvres, communiqué de presse, presse reçue. L’archive de la galerie devient un objet vivant, consultable, citable, lié aux pages artistes.',
    pitchEn: 'Each exhibition gets a page: installation views, work list, press release, press received. The gallery’s archive becomes a living object — browsable, citable, linked to artist pages.',
    forWhoFr: 'Galeries établies dont l’histoire est un argument.',
    forWhoEn: 'Established galleries whose history is an argument.',
    beforeFr: 'Toutes les expositions par année. Filtres par artiste, médium, lieu.',
    beforeEn: 'All exhibitions by year. Filter by artist, medium, venue.',
    duringFr: 'Un panneau par exposition : titre, dates, vues, œuvres, communiqué.',
    duringEn: 'One panel per exhibition: title, dates, views, works, release.',
    afterFr: 'L’archive sert de référence aux institutions et à la presse.',
    afterEn: 'The archive becomes a reference for institutions and press.',
    whyFr: 'L’institution rachète son passé pour vendre son avenir.',
    whyEn: 'An institution leverages its past to sell its future.',
    highlightFr: ['Vues d’installation', 'Communiqués versionnés', 'Lié aux pages artistes'],
    highlightEn: ['Installation views', 'Versioned releases', 'Linked to artist pages'],
    swatchBg: '#E8DCC0', swatchFg: '#3D2E1F', swatchSerif: true,
  },

  // ─────────── OPERATIONS (4 new) ───────────
  {
    slug: 'vault', name: 'Vault', tag: 'Inventory', category: 'operations', comingSoon: true,
    shortFr: 'L’inventaire vivant de toutes vos œuvres.',
    shortEn: 'The living inventory of every work.',
    heroFr: 'Chaque œuvre, sa fiche. Chaque fiche, à jour.',
    heroEn: 'Every work, its record. Every record, current.',
    pitchFr: 'L’inventaire complet : œuvre, dimensions, médium, prix, statut (disponible, réservée, vendue, en consignation), localisation physique, photos, condition reports. La source de vérité de la galerie. Connecté à Bond, Ledger, Booth.',
    pitchEn: 'Full inventory: work, dimensions, medium, price, status (available, reserved, sold, on consignment), physical location, photos, condition reports. The gallery’s source of truth. Connected to Bond, Ledger, Booth.',
    forWhoFr: 'Toute galerie au-delà de 50 œuvres en stock.',
    forWhoEn: 'Any gallery past 50 works in stock.',
    beforeFr: 'Tableau filtrable : artiste, statut, valeur, lieu, date.',
    beforeEn: 'Filterable table: artist, status, value, location, date.',
    duringFr: 'Ajouter une œuvre, attacher des photos, lier un certificat. Statuts en un clic.',
    duringEn: 'Add a work, attach photos, link a certificate. Status in one click.',
    afterFr: 'Vault devient la source de vérité que toutes les autres apps consomment.',
    afterEn: 'Vault becomes the source of truth every other app consumes.',
    whyFr: 'Sans inventaire propre, le reste s’effondre.',
    whyEn: 'Without clean inventory, everything else collapses.',
    highlightFr: ['Statuts du cycle de vie', 'Photos + certificats + condition', 'API pour le reste de Vitreen'],
    highlightEn: ['Lifecycle statuses', 'Photos + certificates + condition', 'API for the rest of Vitreen'],
    swatchBg: '#1A2330', swatchFg: '#9DB4D2',
  },
  {
    slug: 'ledger', name: 'Ledger', tag: 'Sales & invoicing', category: 'operations', comingSoon: true,
    shortFr: 'Ventes, factures, commissions, paiements.',
    shortEn: 'Sales, invoices, commissions, payments.',
    heroFr: 'La compta de la galerie, sans Excel.',
    heroEn: 'Gallery accounts, without Excel.',
    pitchFr: 'Pour chaque vente : facture proforma, facture finale, conditions de paiement, échéancier, calcul automatique des commissions artiste. TVA correctement appliquée selon le pays du collectionneur. Export comptable pour votre expert-comptable.',
    pitchEn: 'For each sale: proforma invoice, final invoice, payment terms, schedule, automatic artist commission calculation. VAT correctly applied per collector country. Accounting export for your accountant.',
    forWhoFr: 'Galeries qui veulent fermer leurs ventes proprement et payer leurs artistes vite.',
    forWhoEn: 'Galleries who want to close sales cleanly and pay artists fast.',
    beforeFr: 'Liste des ventes en cours. Statuts : facturée, payée, commission versée.',
    beforeEn: 'List of pending sales. Statuses: invoiced, paid, commission paid.',
    duringFr: 'Cliquer une œuvre Vault, marquer comme vendue, générer la facture, suivre le paiement.',
    duringEn: 'Click a Vault work, mark as sold, generate the invoice, track payment.',
    afterFr: 'Export PDF pour comptable, export CSV pour banque, paiement de l’artiste en un clic.',
    afterEn: 'PDF export for accountant, CSV for bank, artist payment in one click.',
    whyFr: 'Élimine la double-saisie entre vente et compta.',
    whyEn: 'Eliminates double entry between sale and accounting.',
    highlightFr: ['Facturation TVA conforme', 'Calcul de commissions', 'Export comptable'],
    highlightEn: ['VAT-compliant invoicing', 'Commission calculation', 'Accounting export'],
    swatchBg: '#1B2818', swatchFg: '#C7D89E', swatchSerif: true,
  },
  {
    slug: 'bond', name: 'Bond', tag: 'Collector CRM', category: 'operations', comingSoon: true,
    shortFr: 'Vos collectionneurs : qui ils sont, ce qu’ils aiment, quand les rappeler.',
    shortEn: 'Your collectors: who they are, what they love, when to reach out.',
    heroFr: 'Le carnet noir de la galerie, devenu mémoire vivante.',
    heroEn: 'The gallery’s little black book, made living memory.',
    pitchFr: 'Une fiche par collectionneur : œuvres acquises, œuvres aimées sans acheter, artistes suivis, derniers échanges, prochains rendez-vous. Connecté à Vault et Ledger pour voir l’historique d’achat. Connecté aux Viewing Rooms pour voir ce que vous leur avez envoyé et ce qu’ils ont ouvert.',
    pitchEn: 'One sheet per collector: works acquired, works liked without buying, artists followed, last exchanges, next appointments. Connected to Vault and Ledger for purchase history. Connected to Viewing Rooms to see what you sent and what they opened.',
    forWhoFr: 'Galeries qui considèrent que la relation est l’actif principal.',
    forWhoEn: 'Galleries who consider relationships the primary asset.',
    beforeFr: 'Liste des collectionneurs avec leur dernière interaction et le total dépensé.',
    beforeEn: 'Collector list with last interaction and total spent.',
    duringFr: 'Une fiche par personne : tout ce que vous avez à savoir sur eux, en un écran.',
    duringEn: 'One sheet per person: everything you need to know, in one screen.',
    afterFr: 'Rappels intelligents : « Cela fait 4 mois que vous n’avez rien envoyé à Marina. »',
    afterEn: 'Smart reminders: "It’s been 4 months since you sent anything to Marina."',
    whyFr: 'Les meilleurs galeristes connaissent leurs collectionneurs personnellement. À l’échelle, vous avez besoin d’un cerveau auxiliaire.',
    whyEn: 'The best gallerists know their collectors personally. At scale, you need a second brain.',
    highlightFr: ['Historique d’achats lié à Vault', 'Suivi des envois Viewing Room', 'Rappels intelligents'],
    highlightEn: ['Purchase history linked to Vault', 'Viewing Room send tracking', 'Smart reminders'],
    swatchBg: '#2A1418', swatchFg: '#E8B4B8', swatchSerif: true,
  },
  {
    slug: 'wire', name: 'Wire', tag: 'Newsletter & emails', category: 'operations', comingSoon: true,
    shortFr: 'Vernissages, expositions, fairs : les emails à votre liste, sans Mailchimp.',
    shortEn: 'Openings, exhibitions, fairs: emails to your list, without Mailchimp.',
    heroFr: 'L’invitation au vernissage, élégante par défaut.',
    heroEn: 'The opening invitation, elegant by default.',
    pitchFr: 'Templates pensés pour les communiqués d’art : invitation au vernissage, annonce d’exposition, présence en foire, relance presse. Segmentation par centre d’intérêt artistique. Statistiques d’ouverture qui ne ressemblent pas à un dashboard marketing.',
    pitchEn: 'Templates built for art communications: opening invitations, exhibition announcements, fair presence, press follow-up. Segmentation by artistic interest. Open-rate stats that don’t feel like a marketing dashboard.',
    forWhoFr: 'Galeries qui envoient au moins une newsletter par mois.',
    forWhoEn: 'Galleries that send at least one newsletter a month.',
    beforeFr: 'Listes segmentées : VIP, presse, institutions, public.',
    beforeEn: 'Segmented lists: VIP, press, institutions, public.',
    duringFr: 'Composer dans un éditeur sobre, glisser une œuvre depuis Vault.',
    duringEn: 'Compose in a sober editor, drag a work from Vault.',
    afterFr: 'Envoyer. Statistiques discrètes. Liens vers Bond pour suivre les destinataires actifs.',
    afterEn: 'Send. Discreet stats. Links to Bond to follow active recipients.',
    whyFr: 'Mailchimp n’a jamais été conçu pour annoncer un vernissage.',
    whyEn: 'Mailchimp was never built to announce an opening.',
    highlightFr: ['Templates art-world', 'Segmentation par centre d’intérêt', 'Lié à Bond et Vault'],
    highlightEn: ['Art-world templates', 'Interest-based segmentation', 'Linked to Bond and Vault'],
    swatchBg: '#FFF4D2', swatchFg: '#1A1A1A',
  },

  // ─────────── INSTITUTIONAL (3 new) ───────────
  {
    slug: 'booth', name: 'Booth', tag: 'Art fair logistics', category: 'institutional', comingSoon: true,
    shortFr: 'Foires d’art : sélection, transport, douane, viewing rooms VIP.',
    shortEn: 'Art fairs: selection, transit, customs, VIP viewing rooms.',
    heroFr: 'La foire commence avant la foire, et finit après.',
    heroEn: 'The fair begins before the fair, and ends after it.',
    pitchFr: 'Pour chaque foire : œuvres présélectionnées, plan du stand, viewing rooms pour les VIPs avant l’ouverture, suivi des collectionneurs rencontrés sur place, debrief post-foire. Documents de douane et carnets ATA.',
    pitchEn: 'For each fair: pre-selected works, booth plan, viewing rooms for VIPs before opening, on-site collector tracking, post-fair debrief. Customs documents and ATA carnets.',
    forWhoFr: 'Galeries qui font 3+ foires par an.',
    forWhoEn: 'Galleries doing 3+ fairs a year.',
    beforeFr: 'Calendrier des foires de l’année, statut, nombre d’œuvres présélectionnées.',
    beforeEn: 'Fair calendar for the year, status, pre-selected work count.',
    duringFr: 'Un dossier par foire : sélection, plan, VIP list, viewing rooms par collectionneur.',
    duringEn: 'One folder per fair: selection, plan, VIP list, viewing rooms per collector.',
    afterFr: 'Debrief automatique : œuvres vendues, contacts noués, performance par stand.',
    afterEn: 'Auto debrief: works sold, contacts made, booth performance.',
    whyFr: 'Une foire mal préparée coûte 50 k€ et un trimestre.',
    whyEn: 'A poorly prepared fair costs €50k and a quarter.',
    highlightFr: ['Préparation + suivi + debrief', 'Carnets ATA et douane', 'Viewing rooms VIP intégrées'],
    highlightEn: ['Prep + on-site + debrief', 'ATA carnets and customs', 'Integrated VIP viewing rooms'],
    swatchBg: '#0F2A4A', swatchFg: '#F0F4FA',
  },
  {
    slug: 'pact', name: 'Pact', tag: 'Consignments', category: 'institutional', comingSoon: true,
    shortFr: 'Œuvres en consignation entre galerie et artiste, ou entre galeries.',
    shortEn: 'Works on consignment between gallery and artist, or between galleries.',
    heroFr: 'Les contrats de consignation, signés et suivis.',
    heroEn: 'Consignment agreements, signed and tracked.',
    pitchFr: 'Pour chaque œuvre confiée : contrat numérique signé, durée, conditions de retour, partage des frais (transport, assurance), partage des revenus en cas de vente. Traçabilité complète de l’atelier au mur.',
    pitchEn: 'For each entrusted work: digital signed agreement, duration, return conditions, shared costs (transport, insurance), revenue split on sale. Full traceability from studio to wall.',
    forWhoFr: 'Galeries et représentants d’artistes qui signent vraiment leurs accords.',
    forWhoEn: 'Galleries and artist representatives who actually sign their agreements.',
    beforeFr: 'Liste des consignations en cours, échéances, taux de rotation.',
    beforeEn: 'Active consignments, deadlines, rotation rate.',
    duringFr: 'Créer un contrat depuis un template. Signature électronique. Liaison à Vault.',
    duringEn: 'Create an agreement from a template. E-sign. Linked to Vault.',
    afterFr: 'Vente déclenche le partage automatique des revenus dans Ledger.',
    afterEn: 'Sale triggers automatic revenue sharing in Ledger.',
    whyFr: 'Les conflits artiste-galerie viennent d’accords flous. Pact rend tout explicite.',
    whyEn: 'Artist-gallery conflicts come from fuzzy agreements. Pact makes everything explicit.',
    highlightFr: ['Contrats numériques signés', 'Partage de revenus auto', 'Traçabilité complète'],
    highlightEn: ['Signed digital agreements', 'Auto revenue split', 'Full traceability'],
    swatchBg: '#1A1F3A', swatchFg: '#E8E1D0', swatchSerif: true,
  },
  {
    slug: 'loans', name: 'Loans', tag: 'Museum loans', category: 'institutional', comingSoon: true,
    shortFr: 'Prêts d’œuvres aux musées et fondations.',
    shortEn: 'Loans of works to museums and foundations.',
    heroFr: 'Les œuvres voyagent. Les conditions, l’assurance, le retour : tracés.',
    heroEn: 'The works travel. The conditions, insurance, return: tracked.',
    pitchFr: 'Pour chaque prêt : convention de prêt, valeur d’assurance, conditions climatiques, transporteur, dates aller-retour, condition reports avant et après. Communication directe avec le registraire de l’institution emprunteuse.',
    pitchEn: 'For each loan: loan agreement, insurance value, climate conditions, shipper, outbound and return dates, condition reports before and after. Direct communication with the borrowing institution’s registrar.',
    forWhoFr: 'Galeries établies, estates, fondations qui prêtent régulièrement.',
    forWhoEn: 'Established galleries, estates, foundations that loan regularly.',
    beforeFr: 'Toutes les œuvres en prêt actuellement, avec la date de retour prévue.',
    beforeEn: 'All works on loan, with expected return date.',
    duringFr: 'Convention générée depuis un template institutionnel. Suivi du transport.',
    duringEn: 'Agreement generated from an institutional template. Transit tracking.',
    afterFr: 'Retour : condition report comparé. Litiges éventuels documentés.',
    afterEn: 'Return: condition report comparison. Disputes documented.',
    whyFr: 'Un prêt mal géré peut coûter une œuvre.',
    whyEn: 'A poorly managed loan can cost a work.',
    highlightFr: ['Convention + assurance + transit', 'Condition reports avant/après', 'Communication registraire'],
    highlightEn: ['Agreement + insurance + transit', 'Before/after condition reports', 'Registrar communication'],
    swatchBg: '#3A2D1A', swatchFg: '#E8B95C', swatchSerif: true,
  },
]

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug)
}
export function productsByCategory(c: Category): Product[] {
  return PRODUCTS.filter(p => p.category === c)
}
