/**
 * i18n strings — generated by extracting translations from lang/index.tsx.
 * Keep `as const` to preserve literal type narrowing for useLang() consumers.
 */

export const translations = {
  fr: {
    nav: {
      links: [
        { label: "Gallery OS", href: "#solutions", menu: "product" as const },
        { label: "Solutions", href: "#solutions", menu: "solutions" as const },
        { label: "Tarifs", href: "/pricing" },
        { label: "À propos", href: "/about" },
      ],
      productMenu: {
        sectionLabel: "Produits",
        items: [
          { title: "Artworks Management", desc: "Organisez les œuvres, les artistes et leurs informations.", href: "/products/archive" },
          { title: "Website Publisher", desc: "Publiez les œuvres et les expositions sur votre site.", href: "/products/publishing" },
          { title: "Gallery Assistant", desc: "Préparez vos contenus et le travail quotidien de la galerie.", href: "/products/custom-operations" },
          { title: "Viewing Rooms", desc: "Créez et partagez des sélections privées.", href: "/products/viewing-rooms" },
        ],
        featured: {
          eyebrow: "Sélections privées",
          title: "Viewing Rooms",
          desc: "Créez et partagez des viewing rooms privées à partir de vos fiches d'œuvres.",
          cta: "En savoir plus",
          image: "/screenshot-viewingroom.jpg",
          href: "/products/viewing-rooms",
        },
      },
      solutionsMenu: {
        featured: {
          eyebrow: "À la une",
          title: "Pour les galeries",
          desc: "Un système d’exploitation et un site web connectés pour les galeries d’art contemporain.",
          cta: "En savoir plus",
          image: "/gallery-screen2.png",
          href: "/solutions/galleries",
        },
        columns: [
          {
            label: "Pour qui",
            items: [
              { title: "Galeries", desc: "Œuvres, expositions, demandes", href: "/solutions/galleries" },
              { title: "Conseillers & Marchands", desc: "Sélections privées et suivi client", href: "/solutions/advisors" },
              { title: "Artistes", desc: "Archive, séries, présentation", href: "/solutions/artists" },
              { title: "Collectionneurs", desc: "Acquisitions et documents", href: "/solutions/collectors" },
              { title: "Successions d’artistes", desc: "Corpus, provenance, transmission", href: "/solutions/estates" },
            ],
          },
          {
            label: "Par workflow",
            items: [
              {
                title: "Faire circuler les œuvres",
                desc: "Site, PDF et liens privés",
                href: "/products/publishing",
              },
              {
                title: "Répondre aux collectionneurs",
                desc: "Demandes, réponses et relances",
                href: "/products/custom-operations",
              },
              {
                title: "Préparer une exposition",
                desc: "Œuvres, documents et aperçus",
                href: "/products/viewing-rooms",
              },
              {
                title: "Vos supports de vente",
                desc: "Sélections, fiches et disponibilités",
                href: "#offre",
              },
            ],
          },
        ],
      },
      cta: "Démarrer un projet",
      modal: {
        title: "Nous contacter",
        subtitle: "Décrivez votre projet. Réponse sous 48 h.",
        fields: {
          nom: "Nom",
          galerie: "Galerie",
          email: "Email",
          projet: "Votre projet",
        },
        submit: "Envoyer",
        sending: "Envoi…",
        success: "Merci. Je reviens vers vous très prochainement.",
        close: "Fermer",
        dragHint: "Glissez vers la gauche pour nous écrire",
        ariaLabel:
          "Contactez-nous. Faites glisser le bouton vers la gauche pour ouvrir le formulaire.",
      },
    },
    hero: {
      title: "Votre galerie, là où vous travaillez déjà.",
      subtitle:
        "Gérez vos œuvres, mettez votre site à jour et simplifiez vos ventes aux collectionneurs.",
      ctaPrimary: "Parler de votre galerie",
      ctaSecondary: "Découvrir Gallery OS",
    },
    privateSelections: {
      title: "Viewing Rooms",
      subtitle: "Présentations privées d’œuvres pour les galeries.",
      body:
        "Composez des sélections prêtes à partager à partir de vos fiches d’œuvres, générez des liens privés, exportez en PDF et diffusez vos présentations par email ou WhatsApp.",
      cta: "En savoir plus",
      mock: {
        label: "Sélection privée",
        artist: "Sacha Elron",
        title: "Untitled (Horizon)",
        year: "2024",
        medium: "Huile sur toile",
        dimensions: "152 × 122 cm",
        inquire: "Demander des informations",
      },
    },
    artworkSource: {
      kicker: "Couche opérationnelle",
      title: "A gallery infrastructure, not another platform.",
      body:
        "Chaque galerie gère ses œuvres, collectionneurs et ventes différemment. Vitreen s’adapte à vos sources existantes, vos habitudes de communication et vos workflows relationnels — et les transforme en une couche opérationnelle plus claire.",
      connectedLabel: "Côté archive",
      connectedTitle: "Gardez vos sources existantes",
      connectedBody:
        "Fonctionne avec votre système actuel, les fichiers CSV, les archives internes et les dossiers partagés.",
      orLabel: "→",
      nativeLabel: "Côté collectionneurs",
      nativeTitle: "Activez chaque œuvre",
      nativeBody:
        "Diffusez via Gmail, WhatsApp, liens privés et PDFs, sans ajouter une nouvelle plateforme à apprendre pour l’équipe.",
      note:
        "Vitreen est conçu pour se placer entre l’archive et les conversations collectionneurs. La galerie garde son workflow actuel ; Vitreen rend les œuvres, les échanges et les demandes plus faciles à activer.",
      features: [
        {
          label: "01",
          title: "Artwork Sync",
          copy: "Importez les œuvres sélectionnées depuis la base existante de la galerie, un CSV ou un ajout manuel.",
          image: "/gallery hero mock/artwork-02.png",
        },
        {
          label: "02",
          title: "Private Materials",
          copy: "Générez des PDFs soignés, liens privés ou viewing rooms à partir des œuvres sélectionnées.",
          image: "/viewing-room-share.png",
        },
        {
          label: "03",
          title: "Collector Sharing",
          copy: "Envoyez les œuvres par email, WhatsApp ou lien privé sans changer le workflow de la galerie.",
          image: "/gallery hero mock/shoes-exhibition.png",
        },
        {
          label: "04",
          title: "Inquiry Capture",
          copy: "Permettez aux collectionneurs de répondre, demander des détails ou faire une demande depuis le support partagé.",
          image: "/artworks/painting-06.png",
        },
        {
          label: "05",
          title: "Sales Routing",
          copy: "Redirigez les signaux collectionneurs vers la bonne personne dans l’équipe galerie.",
          image: "/gallery hero mock/frieze-newyork-booth.png",
        },
      ],
    },
    audiences: {
      tabs: ["Galeries", "Artistes", "Art Advisors", "Collection Privée"],
      soon: "Soon",
      items: [
        {
          title: "Une vitrine à la hauteur de votre programme.",
          description:
            "Présentez vos artistes, archivez vos expositions, gérez votre catalogue en ligne — sans compétences techniques.",
          features: [
            "Catalogue d\u2019œuvres",
            "Pages artistes",
            "Archives d\u2019expositions",
            "Formulaire de contact",
          ],
        },
        {
          title: "Votre œuvre mérite un espace à elle.",
          description:
            "Un portfolio conçu pour vous — biographie, CV d\u2019exposition, séries d\u2019œuvres — mis à jour par vous, sans intermédiaire.",
          features: [
            "Portfolio en ligne",
            "Séries et œuvres",
            "CV d\u2019exposition",
            "Prise de contact directe",
          ],
        },
        {
          title: "Partagez des sélections, pas des fichiers.",
          description:
            "Présentez vos recommandations à vos clients dans un espace professionnel, confidentiel et facile à naviguer.",
          features: [
            "Partage de sélections",
            "Espaces clients",
            "Fiches d\u2019œuvres détaillées",
            "Interface confidentielle",
          ],
        },
        {
          title: "Votre collection, organisée et accessible.",
          description:
            "Centralisez l\u2019ensemble de vos œuvres dans un espace privé : fiches, documents, historique — tout en un lieu.",
          features: [
            "Inventaire complet",
            "Fiches détaillées",
            "Documents associés",
            "Accès sécurisé",
          ],
        },
      ],
    },
    showcase: {
      title: "Et en coulisses, un espace de travail connecté aux galeries.",
      subtitle:
        "Demandes, expositions, œuvres. Le nécessaire pour publier, partager et suivre.",
      cards: [
        {
          title: "Les demandes, reliées aux œuvres.",
          desc: "Chaque demande arrive avec le contexte utile : artiste, œuvre, sélection privée ou viewing room.",
        },
        {
          title: "Préparez les expositions une seule fois.",
          desc: "Les œuvres sélectionnées alimentent les pages, les viewing rooms et les présentations collectionneurs.",
        },
        {
          title: "Des données prêtes à circuler.",
          desc: "Prix, statut, médium et informations artistes restent disponibles pour les surfaces collector-facing.",
        },
      ],
      bio: [
        "Sacha Elron (né en 1960 à Oklahoma City, Oklahoma) est un peintre américain reconnu pour ses paysages méditatifs à grande échelle. Formé à la peinture figurative à l\u2019Art Students League de New York, il développe rapidement un langage visuel personnel, oscillant entre représentation et abstraction pure.",
        "Son œuvre prend racine dans la contemplation de la nature — ciels vastes, horizons lumineux, arbres solitaires — qu\u2019il distille en champs de couleur saturés, denses et silencieux. Travaillant principalement à l\u2019huile sur toile, Sacha Elron construit ses tableaux par couches successives de pigments, laissant parfois transparaître les strates sous-jacentes comme autant de traces du temps.",
        "Ses expositions personnelles se sont tenues dans des galeries majeures à New York, Los Angeles, Paris et Berlin. Ses œuvres figurent dans de nombreuses collections publiques et privées, notamment au Whitney Museum of American Art, au Musée d\u2019Art Moderne de Paris, et dans plusieurs fondations européennes dédiées à la peinture contemporaine.",
        "En 2008, il reçoit le Prix de la Fondation Pollock-Krasner, récompense majeure du monde de l\u2019art américain. En 2015, une rétrospective lui est consacrée à la Fondation Beyeler à Bâle, rassemblant plus de 80 œuvres couvrant trente ans de pratique.",
        "Sacha Elron vit et travaille à Brooklyn, New York, dans un atelier qu\u2019il occupe depuis 1994.",
      ],
      readBio: "Lire la biographie complète",
    },
    solution: {
      title: "Chaque œuvre, partout où elle compte.",
      subtitle:
        "Mettez à jour votre site, vos sélections privées et les demandes des collectionneurs depuis un seul endroit.",
      cards: [
        {
          title: "Demande d’information",
          desc: "Chaque œuvre ouvre une conversation privée avec la galerie, sans panier ni paiement en ligne.",
        },
        {
          title: "Partage privé",
          desc: "Envoyez une viewing room dans un email soigné, avec une demande d’information sur chaque œuvre.",
        },
        {
          title: "Sélections collectionneurs",
          desc: "Ajoutez des œuvres à une sélection depuis la conversation et partagez-la en PDF prêt à l’emploi.",
        },
      ],
      mock: {
        artworkManagement: "Gestion des œuvres",
        medium: "Huile sur toile",
        inquire: "Demander des informations",
        onRequest: "Sur demande",
        synced: "Synchronisé",
        importing: "IMPORTATION",
      },
    },
    homeAddIns: {
      title: "Répondre, partager, envoyer.",
      subtitle:
        "Utilisez les mêmes informations d’œuvres dans Gmail, WhatsApp et vos PDF.",
      cards: {
        gmail: {
          title: "Gmail",
          description:
            "Recherchez une œuvre et insérez ses informations directement dans un email.",
        },
        whatsapp: {
          title: "WhatsApp",
          description:
            "Transformez une sélection d’œuvres en PDF propre, prêt à être envoyé.",
        },
        excel: {
          title: "Excel",
          description:
            "Synchronisez vos feuilles d’inventaire existantes avec des fiches d’œuvres structurées.",
        },
      },
    },
    signatureDemo: {
      title: "Une œuvre, partagée sur chaque surface de la galerie.",
      subtitle:
        "Changez son prix une fois et le site, le PDF et la viewing room se mettent à jour avec elle.",
      sourceLabel: "Gallery OS",
      priceLabel: "Prix",
      statusLabel: "Disponibilité",
      available: "Disponible",
      saved: "Enregistré",
      outputs: [
        { label: "Site", status: "À jour" },
        { label: "PDF", status: "À jour" },
        { label: "Viewing Room", status: "À jour" },
      ],
    },
    processFlow: {
      title: "On part de votre galerie existante.",
      subtitle: "On adapte Vitreen à la façon dont votre équipe travaille.",
      steps: [
        {
          number: "01",
          title: "Commencez depuis votre configuration existante",
          desc: "Connectez votre système actuel, vos fichiers CSV ou vos tableurs, ou gérez les œuvres directement dans la bibliothèque Vitreen.",
          week: "CONNEXION",
        },
        {
          number: "02",
          title: "Préparez les œuvres pour la publication",
          desc: "Les données d’œuvres sont structurées pour les expositions, viewing rooms, sélections privées, PDFs et publications web.",
          week: "STRUCTURATION",
        },
        {
          number: "03",
          title: "Partagez et suivez en continu",
          desc: "Publiez, envoyez et suivez les supports destinés aux collectionneurs depuis la même source d’œuvres.",
          week: "EXPLOITATION",
        },
      ],
    },
    stepper: {
      title: "Publier du contenu, sans effort",
      subtitle:
        "Vous publiez en autonomie. Ajoutez vos œuvres, elles apparaissent instantanément sur votre site.",
      steps: [
        {
          title: "Ajoutez une œuvre",
          desc: "Formulaire simple, publié en un clic.",
        },
        {
          title: "Site mis à jour",
          desc: "L\u2019œuvre apparaît instantanément, sans code.",
        },
        {
          title: "Partagez",
          desc: "Lien, Viewing Room privé, email collectionneurs.",
        },
      ],
      mock: {
        admin: {
          workspace: "Mon espace galerie",
          online: "En ligne",
          sidebar: ["Œuvres", "Artistes", "Expositions", "Viewing Rooms"],
          newArtwork: "Nouvelle œuvre",
          publish: "Publier",
          titleField: "Titre",
          artistField: "Artiste",
          imageField: "Image",
          dragClick: "Glissez ou cliquez",
          priceField: "Prix",
          priceValue: "Sur demande",
          dimField: "Dimensions",
        },
        livesite: {
          navItems: ["Œuvres", "Artistes", "Expositions", "Contact"],
          technique: "Technique",
          techniqueValue: "Huile sur toile",
          dimensions: "Dimensions",
          price: "Prix",
          priceValue: "Sur demande",
          inquire: "Demander le prix",
          liveStatus: "Visible en ligne — mis à jour il y a 2 secondes",
        },
        share: {
          newMessage: "Nouveau message",
          notifyCollector: "Notifier un collectionneur",
          from: "De",
          to: "À",
          subject: "Objet",
          artworkSub: "Claire Fontaine · Sur demande",
          send: "Envoyer",
          sent: "Envoyé",
          recipientsCount: "1 sur 3 collectionneurs",
        },
      },
    },
    services: {
      title: "Ce que vous recevez",
      subtitle: "Un Gallery OS connecté, construit autour de votre fonctionnement.",
      cards: {
        website: { label: "Site connecté", title: "Site web" },
        dashboard: { label: "Œuvres", title: "Base de données" },
        pdf: { label: "Supports collectionneurs", title: "Éditeur de sélections privées" },
        addins: { label: "Extensions", title: "Gallery OS dans Gmail et WhatsApp." },
        gmail: { label: "Gmail", title: "Vos œuvres dans vos emails." },
        whatsapp: { label: "WhatsApp", title: "Vos sélections prêtes à envoyer." },
      },
      items: [
        {
          tier: "gallery-os",
          name: "Votre Gallery OS connecté",
          description:
            "Un site connecté, un tableau de bord pour vos œuvres et les outils pour préparer vos échanges collectionneurs.",
          featuresHeading: "INCLUS",
          features: [
            "Audit du fonctionnement de la galerie",
            "Site connecté aux fiches d’œuvres",
            "Tableau de bord des œuvres",
            "Extensions Gmail et WhatsApp",
            "Export PDF simple",
            "Sélections privées pour collectionneurs",
          ],
          delivery: undefined as string | undefined,
          cta: "Parlons-en",
          highlight: false as const,
        },
      ],
    },
    pricingBand: {
      title: "Un prix clair.",
      subtitle: "Une seule offre, tout compris.",
      pilotPill: "Programme pilote — 3 places · installation à −50 %",
      base: {
        title: "Gallery OS",
        description: "Votre système complet, construit autour de votre galerie.",
        price: "5 000 €",
        priceDetail: "Installation unique, incluant la mise en œuvre et la première année de support.",
        features: [
          "Dashboard des œuvres, artistes et expositions",
          "Site connecté à vos fiches d’œuvres",
          "Extensions Gmail et WhatsApp",
          "Exports PDF et sélections privées",
          "Migration de vos données incluse",
          "Hébergement, mises à jour et support",
        ],
        note: "Livré en ~3 semaines",
        cta: "Parlons-en",
      },
      partner: {
        title: "Option Partner",
        description: "Pour les galeries qui préfèrent déléguer le quotidien.",
        price: "+350 €/mois",
        priceDetail: "Accompagnement continu pour faire vivre et améliorer votre Gallery OS.",
        features: [
          "Un point mensuel avec votre interlocuteur dédié",
          "Mises à jour de contenu faites pour vous",
          "Préparation de vos supports collectionneurs",
          "Nouvelles pages et sections à la demande",
          "Support prioritaire",
        ],
      },
      pricingLink: "Voir le détail →",
    },
    pricing: {
      hero: {
        title: "Un prix clair, un périmètre défini ensemble.",
        subtitle: "Une seule offre : votre Gallery OS installé, puis un abonnement simple.",
      },
      offer: {
        eyebrow: "Une offre unique",
        title: "Gallery OS",
        description: "Votre système complet, construit autour de votre galerie.",
        price: "5 000 €",
        priceDetail: "installation, paiement unique",
        features: [
          "Dashboard des œuvres, artistes et expositions",
          "Site connecté à vos fiches d’œuvres",
          "Extensions Gmail et WhatsApp",
          "Exports PDF et sélections privées",
          "Migration de vos données incluse",
          "Hébergement, mises à jour et support",
        ],
        deliveryNote: "Livré en ~3 semaines",
        note:
          "Le périmètre exact se définit lors d’un premier échange — c’est lui qui précise le devis.",
      },
      partnerOption: {
        eyebrow: "Option",
        title: "Partner",
        description: "Pour les galeries qui préfèrent déléguer le quotidien.",
        price: "+350 €/mois",
        qualifier: "en complément de votre Gallery OS",
        cta: "Ajouter Partner",
        features: [
          "Un point mensuel avec votre interlocuteur dédié",
          "Mises à jour de contenu faites pour vous",
          "Préparation de vos supports collectionneurs",
          "Nouvelles pages et sections à la demande",
          "Support prioritaire",
        ],
      },
      pilot: {
        eyebrow: "Programme pilote",
        title: "Trois galeries pilotes",
        body:
          "Les trois premières galeries bénéficient d’une installation à tarif pilote, en échange d’une étude de cas publiée.",
        referencePrice: "5 000 €",
        discount: "−50 %",
        price: "2 500 €",
        availability: "3 places — premier arrivé, premier servi.",
        cta: "Parlons-en",
      },
      costAnchor: {
        title: "Ce que remplace Vitreen",
        items: [
          {
            title: "Outil d’inventaire",
            cost: "Environ 200–300 €/mois",
            description: "Pour stocker et maintenir les fiches d’œuvres.",
          },
          {
            title: "Agence ou prestataire web",
            cost: "Environ 4 000–8 000 € + frais par modification",
            description: "Pour construire le site puis intervenir à chaque changement.",
          },
          {
            title: "Ressaisie par l’équipe",
            cost: "Plusieurs heures chaque semaine",
            description: "Pour recopier les mêmes informations dans le site, les PDF et les emails.",
          },
        ],
        conclusion: "Un système, un interlocuteur.",
      },
      faq: {
        title: "Questions sur l’offre",
        items: [
          {
            q: "À qui appartiennent mes données ?",
            a: "À vous. Un export complet est possible à tout moment.",
          },
          {
            q: "Pourquoi un engagement de 12 mois ?",
            a: "L’accompagnement mensuel est ce qui garde le système vivant ; l’installation seule ne suffit pas.",
          },
          {
            q: "Que se passe-t-il si j’arrête ?",
            a: "Vous repartez avec vos données et vos contenus.",
          },
          {
            q: "Combien de temps dure l’installation ?",
            a: "Environ trois semaines, du premier échange à la mise en ligne.",
          },
          {
            q: "Qui fait les mises à jour au quotidien ?",
            a: "Vous, en autonomie. Et si vous préférez déléguer, l’option Partner s’en charge pour vous.",
          },
        ],
      },
      cta: "Parlons-en",
    },
    statementSplit: {
      statTitle: "L\u2019art en ligne red\u00e9finit l\u2019\u00e9conomie du march\u00e9 de l\u2019art",
      stats: [
        {
          value: "$10,5Mds",
          label: "Ventes en ligne en 2024",
          sub: "March\u00e9 mondial",
        },
        { value: "18%", label: "Du march\u00e9 total", sub: "Part du digital" },
        { value: "+76%", label: "Vs avant-pand\u00e9mie", sub: "Depuis 2019" },
        { value: "40,5M", label: "Transactions en 2024", sub: "+3% sur un an" },
      ],
      amplifyTitle: "Amplifiez l\u2019influence de votre galerie",
      blocks: [
        {
          heading: "Standardisez votre pr\u00e9sence en ligne.",
          body1:
            "Sans canal d\u2019achat \u00e0 la hauteur, vous restez hors du champ des collectionneurs qui d\u00e9cident d\u00e9j\u00e0 en ligne \u2014 partout dans le monde.",
          body2:
            "Vitreen d\u00e9ploie une distribution native, permettant d\u2019exposer, diffuser et rendre accessibles vos \u0153uvres en continu, sans d\u00e9pendre des circuits traditionnels.",
        },
        {
          heading: "Transformez l\u2019attention en engagement durable.",
          body1:
            "Des parcours pens\u00e9s pour faire passer l\u2019int\u00e9r\u00eat \u00e0 l\u2019achat : moins de friction, des choix plus nets, des actions qui comptent.",
          body2:
            "Chaque interaction accompagne un glissement progressif \u2014 de la d\u00e9couverte vers l\u2019engagement, et de l\u2019attention vers une relation durable avec le travail de l\u2019artiste.",
        },
        {
          heading: "Reprenez le contr\u00f4le de votre relation.",
          body1:
            "Donn\u00e9es, \u00e9changes et historique avec chaque collectionneur se retrouvent au m\u00eame endroit \u2014 fini les informations \u00e9parpill\u00e9es entre mails et outils.",
          body2:
            "Vitreen relie vos \u0153uvres, s\u00e9lections et demandes pour rendre chaque \u00e9change plus lisible et plus facile \u00e0 suivre.",
        },
      ],
    },
    quoteSection: {
      quote:
        "L\u2019espace num\u00e9rique est le prolongement naturel de la vitrine de la galerie. \u00c0 l\u2019heure actuelle, un programme en ligne solide et une strat\u00e9gie d\u00e9di\u00e9e sont essentiels dans le monde de l\u2019art.",
      name: "Elena Soboleva",
      role: "Responsable mondiale de la croissance des audiences et de l’intelligence, Art Basel",
    },
    faq: {
      title: "Questions fréquentes",
      items: [
        {
          q: "Puis-je modifier le site moi-même ?",
          a: "Oui, via une interface simple. Pas besoin de compétences techniques — vous gérez vos contenus en autonomie.",
        },
        {
          q: "Combien de temps prend la mise en ligne ?",
          a: "Environ 3 semaines, du premier échange à la mise en ligne.",
        },
        {
          q: "Dois-je utiliser un logiciel spécifique ?",
          a: "Non. Vitreen peut se connecter à un inventaire existant ou utiliser la Vitreen Artwork Library comme source d’œuvres.",
        },
        {
          q: "Que se passe-t-il si je veux arrêter ?",
          a: "Le partenariat est conclu pour 12 mois afin d’inclure l’hébergement, les mises à jour et l’accompagnement mensuel.",
        },
        {
          q: "Est-ce que Vitreen s\u2019occupe du contenu ?",
          a: "Oui. L’accompagnement mensuel peut inclure la publication du catalogue, la préparation des actualités et la structuration de vos emails, tout en vous laissant la main sur vos contenus.",
        },
        {
          q: "Mon site sera-t-il visible sur Google ?",
          a: "Oui. Chaque site est optimisé pour le SEO dès le départ : structure sémantique, balises meta, images optimisées et indexation adaptée au marché de l\u2019art.",
        },
      ],
    },
    tools: {
      sectionLabel: "Outils",
      backToHome: "Retour à l’accueil",
      featuresLabel: "Inclus",
      overview: {
        eyebrow: "Outils · Overview",
        title: "Une vue connectée des outils Vitreen.",
        subtitle: "Outils connectés pour expositions, publication et communication collectionneurs.",
        body:
          "Vitreen rassemble les outils dont une galerie a besoin pour publier des œuvres, préparer des présentations privées, partager des sélections et suivre les demandes — sans changer les habitudes de l’équipe.",
        features: [
          "Une seule source d’œuvres",
          "Publication web, PDFs et viewing rooms",
          "Partage privé pour collectionneurs",
          "Suivi des demandes par œuvre",
        ],
        cta: "Parlons-en",
      },
      archive: {
        eyebrow: "Outils · Artworks Management",
        title: "Artworks Management",
        subtitle: "Œuvres, artistes et expositions organisés autour de votre workflow.",
        body:
          "Archive sert de base structurée pour les œuvres de la galerie : artistes, expositions, médiums, dimensions, statuts. Les données restent disponibles pour les pages publiques, les viewing rooms et les supports envoyés aux collectionneurs.",
        features: [
          "Fiches œuvres, artistes et expositions",
          "Statuts, prix et disponibilités",
          "Médiums, dimensions et provenance",
          "Connexion possible à un inventaire existant",
        ],
        cta: "Parlons-en",
      },
      "viewing-rooms": {
        eyebrow: "Outils · Viewing Rooms",
        title: "Présentations privées pour collectionneurs.",
        subtitle: "Présentations privées pour collectionneurs et expositions.",
        body:
          "Préparez une sélection d’œuvres dans un espace privé : contexte d’exposition, fiches détaillées et lien partageable. Les viewing rooms s’ouvrent sur invitation, dans une interface lisible et confidentielle.",
        features: [
          "Sélection privée par collectionneur",
          "Contexte d’exposition et fiches œuvres",
          "Lien à durée et accès limités",
          "Demande directe depuis chaque œuvre",
        ],
        cta: "En savoir plus",
        badge: "Bientôt",
      },
      previews: {
        eyebrow: "Outils · Previews",
        title: "Présentations privées d’œuvres.",
        subtitle: "Présentations privées d’œuvres pour collectionneurs.",
        body:
          "Composez rapidement un aperçu d’œuvres à envoyer avant une foire, une exposition ou une rencontre. Une mise en page sobre, partagée par lien privé, email ou WhatsApp.",
        features: [
          "Sélection rapide d’œuvres",
          "Fiches d’œuvre soignées",
          "Partage par lien, email ou WhatsApp",
          "Export PDF prêt à envoyer",
        ],
        cta: "Parlons-en",
      },
      publishing: {
        eyebrow: "Outils · Publishing",
        title: "Publier depuis une seule source.",
        subtitle: "Pages web, PDFs et communication collectionneurs depuis la même structure d’œuvres.",
        body:
          "Publishing transforme les données d’œuvres en pages publiques, archives d’expositions, PDFs et emails envoyés aux collectionneurs — sans saisir les informations deux fois.",
        features: [
          "Pages œuvres, artistes et expositions",
          "Archives d’expositions",
          "Exports PDF et présentations imprimables",
          "Emails collectionneurs construits depuis les œuvres",
        ],
        cta: "Parlons-en",
      },
      inquiries: {
        eyebrow: "Outils · Inquiries",
        title: "Suivre l’intérêt collectionneur.",
        subtitle: "Suivez l’intérêt collectionneur à travers œuvres et partages privés.",
        body:
          "Inquiries rattache chaque demande à une œuvre, une viewing room ou une sélection privée. La galerie garde le contexte utile pour répondre : qui, sur quoi, depuis quel partage.",
        features: [
          "Demandes liées aux œuvres",
          "Contexte de viewing room ou sélection",
          "Statut, suivi et notes internes",
          "Compatible avec les outils clients existants",
        ],
        cta: "Parlons-en",
      },
      mobile: {
        eyebrow: "Outils · Mobile",
        title: "La galerie publie depuis son téléphone.",
        subtitle: "Publication galerie, même en déplacement.",
        body:
          "Mobile permet à la galerie de publier une œuvre, mettre à jour une fiche ou préparer un partage privé depuis son téléphone — sur un stand, en transit ou pendant un accrochage.",
        features: [
          "Ajout d’une œuvre depuis le téléphone",
          "Mise à jour rapide d’une fiche",
          "Partage privé en quelques pressions",
          "Suivi des demandes en mobilité",
        ],
        cta: "Parlons-en",
      },
      "custom-operations": {
        eyebrow: "Outils · Custom Operations",
        title: "Adapter Vitreen au workflow de la galerie.",
        subtitle: "Workflows sur mesure adaptés à votre galerie.",
        body:
          "Custom Operations permet d’ajuster Vitreen aux opérations propres à la galerie : champs spécifiques, intégrations à des outils existants, automatisations internes ou modèles de partage propres au programme.",
        features: [
          "Champs et statuts personnalisés",
          "Intégrations avec outils existants",
          "Automatisations internes",
          "Modèles de partage propres à la galerie",
        ],
        cta: "Parlons-en",
      },
    },
    solutions: {
      sectionLabel: "Solutions",
      backToHome: "Retour à l’accueil",
      featuresLabel: "Inclus",
      relatedLabel: "Par profil",
      mockCaption: "Aperçu",
      galleries: {
        eyebrow: "Galeries",
        title: "Pensé autour de la façon dont votre galerie travaille déjà.",
        subtitle: "Œuvres, expositions et demandes réunies dans une couche opérationnelle connectée.",
        body:
          "Vitreen connecte les archives, inventaires ou bases de données existants de la galerie, puis transforme les œuvres en matériel collector prêt à partager — viewing rooms, sélections privées, PDFs — sans remplacer vos outils.",
        features: [
          "Connexion à vos archives, inventaires ou bases existantes",
          "Œuvres transformées en viewing rooms, PDFs et liens privés",
          "Demandes rattachées aux bonnes œuvres",
          "Passage fluide entre publication publique et partage privé",
        ],
        cta: "Parlons-en",
      },
      advisors: {
        eyebrow: "Conseillers & marchands",
        title: "Présentez les bonnes œuvres à chaque client.",
        subtitle:
          "Créez des sélections privées depuis vos fiches œuvres, partagez-les par lien ou PDF et gardez chaque échange relié aux œuvres.",
        body: "",
        features: [
          "Sélection privée par client",
          "Partage par lien privé, PDF ou WhatsApp",
          "Suivi rattaché à chaque œuvre",
          "Présentation des œuvres sans révéler vos sources",
        ],
        cta: "Parlons-en",
      },
      artists: {
        eyebrow: "Artistes",
        title: "Une archive qui présente votre travail clairement.",
        subtitle: "Archive, séries et présentation, structurées autour de votre œuvre.",
        body:
          "Pour les artistes et les studios, structurez le corpus — séries, médiums, années, provenance — et présentez une sélection aux galeries, commissaires ou collectionneurs via des liens privés.",
        features: [
          "Gardez votre travail organisé",
          "Faites en sorte que votre site reflète votre pratique actuelle",
          "Soyez prêt quand une opportunité se présente",
          "Votre assistant d’atelier",
        ],
        cta: "Parlons-en",
      },
      collectors: {
        eyebrow: "Solutions · Collectionneurs",
        title: "Votre collection, documentée et à portée de main.",
        subtitle: "Acquisitions et documents réunis, viewing rooms reçues des galeries.",
        body:
          "Pour les collectionneurs, gardez acquisitions, documents et informations d’état au même endroit, et recevez des viewing rooms privées des galeries avec lesquelles vous travaillez.",
        features: [
          "Acquisitions et documents réunis en un lieu",
          "Factures, certificats et constats d’état conservés",
          "Réception de viewing rooms privées des galeries",
          "Examen des œuvres proposées avant acquisition",
        ],
        cta: "Parlons-en",
      },
      estates: {
        eyebrow: "Successions d’artistes",
        title: "La gestion d’un corpus complet d’œuvres.",
        subtitle: "Corpus, provenance et transmission, sous votre contrôle.",
        body:
          "Pour les successions d’artistes et fondations, structurez l’ensemble du corpus, préservez la provenance et l’historique d’expositions, et maîtrisez la façon dont les œuvres sont présentées aux institutions et collectionneurs.",
        features: [
          "Structuration du corpus complet",
          "Provenance et historique d’expositions préservés",
          "Contrôle de la présentation des œuvres",
          "Préparation des prêts, ventes et demandes institutionnelles",
        ],
        cta: "Parlons-en",
      },
    },
    ctaBand: {
      title: "Commencez avec votre fonctionnement actuel",
      subtitle: "Ajoutez les outils dont votre galerie a besoin",
      cta: "Parler à Vitreen",
    },
    about: {
      eyebrow: "À propos de Vitreen",
      title: "Aider les galeries à construire des opérations plus solides.",
      lead: "La prochaine génération de galeries devra faire plus que bien présenter l’art.",
      letter: {
        title: "Un mot du fondateur",
        paragraphs: [
          "Le marché de l’art repose encore sur les relations, le jugement et la confiance. Cela ne devrait pas changer.",
          "Mais le travail opérationnel derrière ces relations devient plus lourd.",
          "On attend des petites galeries qu’elles tiennent des fiches d’œuvres justes, un site à jour, une communication soignée avec leurs collectionneurs et du matériel privé irréprochable — souvent avec une équipe très réduite.",
          "Vitreen a été créé pour leur donner une meilleure infrastructure.",
          "Nous relions l’information des œuvres aux endroits où la galerie travaille déjà : son site, ses emails, ses PDFs, ses sélections privées et ses conversations avec les collectionneurs.",
          "L’objectif n’est pas de remplacer la part humaine de la galerie. C’est de la soutenir.",
          "Quand l’information est organisée et prête à l’emploi, l’équipe répond plus vite, relance plus régulièrement et passe plus de temps à construire des relations.",
          "Pour les galeries établies, Vitreen renforce les opérations existantes.",
          "Pour une nouvelle génération de galeristes, il offre un moyen de démarrer avec les capacités d’une structure plus grande, sans en porter les coûts.",
          "Nous pensons que les galeries qui resteront compétitives ne seront pas celles qui utilisent le plus de technologie. Ce seront celles qui l’utilisent avec le plus de clarté.",
        ],
        signature: { name: "Raphaël Rossi", role: "Fondateur, Vitreen" },
      },
      audiences: [
        {
          title: "Pour les galeries établies",
          text: "Vitreen renforce les opérations existantes.",
        },
        {
          title: "Pour les galeristes qui débutent",
          text: "Il apporte l’infrastructure pour démarrer professionnellement sans constituer une grande équipe dès le premier jour.",
        },
      ],
      cta: "Parlons-en",
    },
    footer: {
      tagline: "Sites connectés et outils de vente pour galeries d’art, artistes et conseillers.",
      columns: {
        platform: "Plateforme",
        solutions: "Solutions",
        company: "Vitreen",
      },
      links: {
        galleryOs: "Gallery OS",
        artworkManagement: "Gestion des œuvres",
        galleryWebsites: "Sites de galerie",
        viewingRooms: "Viewing rooms privées",
        galleryAssistant: "Assistant de galerie",
        forGalleries: "Pour les galeries",
        forArtists: "Pour les artistes",
        forAdvisors: "Pour les conseillers et marchands",
        about: "À propos",
        pricing: "Tarifs",
        contact: "Contact",
      },
      location: "Paris, France",
    },
  },
  en: {
    nav: {
      links: [
        { label: "Gallery OS", href: "#solutions", menu: "product" as const },
        { label: "Solutions", href: "#solutions", menu: "solutions" as const },
        { label: "Pricing", href: "/pricing" },
        { label: "About", href: "/about" },
      ],
      productMenu: {
        sectionLabel: "Products",
        items: [
          { title: "Artworks Management", desc: "Organise artworks, artists and records.", href: "/products/archive" },
          { title: "Website Publisher", desc: "Publish artworks and exhibitions online.", href: "/products/publishing" },
          { title: "Gallery Assistant", desc: "Prepare content and daily gallery work.", href: "/products/custom-operations" },
          { title: "Viewing Rooms", desc: "Create and share private selections.", href: "/products/viewing-rooms" },
        ],
        featured: {
          eyebrow: "Private selections",
          title: "Viewing Rooms",
          desc: "Build and share private viewing rooms from your artwork records.",
          cta: "See more",
          image: "/screenshot-viewingroom.jpg",
          href: "/products/viewing-rooms",
        },
      },
      solutionsMenu: {
        featured: {
          eyebrow: "Featured",
          title: "For Art Galleries",
          desc: "A connected operating system and website for contemporary galleries.",
          cta: "See more",
          image: "/gallery-screen2.png",
          href: "/solutions/galleries",
        },
        columns: [
          {
            label: "For who",
            items: [
              { title: "Galleries", desc: "Artworks, exhibitions, inquiries", href: "/solutions/galleries" },
              { title: "Advisors & Dealers", desc: "Private selections and client follow-up", href: "/solutions/advisors" },
              { title: "Artists", desc: "Archive, series, presentation", href: "/solutions/artists" },
              { title: "Collectors", desc: "Acquisitions and documents", href: "/solutions/collectors" },
              { title: "Artist Estates", desc: "Corpus, provenance, transmission", href: "/solutions/estates" },
            ],
          },
          {
            label: "By workflow",
            items: [
              {
                title: "Circulate artworks",
                desc: "Website, PDFs and private links",
                href: "/products/publishing",
              },
              {
                title: "Reply to collectors",
                desc: "Inquiries, replies and reminders",
                href: "/products/custom-operations",
              },
              {
                title: "Prepare an exhibition",
                desc: "Works, documents and previews",
                href: "/products/viewing-rooms",
              },
              {
                title: "Sales materials",
                desc: "Selections, sheets and availability",
                href: "#offre",
              },
            ],
          },
        ],
      },
      cta: "Start a project",
      modal: {
        title: "Get in touch",
        subtitle:
          "Tell us about your project. We\u2019ll reply within 48 hours.",
        fields: {
          nom: "Name",
          galerie: "Gallery",
          email: "Email",
          projet: "Your project",
        },
        submit: "Send",
        sending: "Sending\u2026",
        success: "Thank you. I\u2019ll get back to you shortly.",
        close: "Close",
        dragHint: "Swipe left to get in touch",
        ariaLabel: "Contact us. Swipe the button to the left to open the form.",
      },
    },
    hero: {
      title: "Your gallery, wherever you already work.",
      subtitle:
        "Connect your artwork records to your website, private selections and collector conversations.",
      ctaPrimary: "Discuss your gallery",
      ctaSecondary: "Explore Gallery OS",
    },
    privateSelections: {
      title: "Viewing Rooms",
      subtitle: "Private artwork presentations for galleries.",
      body:
        "Create collector-ready selections from your artwork records, generate private links, export PDFs and distribute presentations instantly by email or WhatsApp.",
      cta: "See more",
      mock: {
        label: "Private selection",
        artist: "Sacha Elron",
        title: "Untitled (Horizon)",
        year: "2024",
        medium: "Oil on canvas",
        dimensions: "152 × 122 cm",
        inquire: "Inquire",
      },
    },
    artworkSource: {
      kicker: "Operational layer",
      title: "A gallery infrastructure, not another platform.",
      body:
        "Every gallery handles artworks, collectors and sales differently. Vitreen adapts to your existing sources, communication habits and relationship-driven workflows — then turns them into a clearer operating layer.",
      connectedLabel: "Archive side",
      connectedTitle: "Keep your existing sources",
      connectedBody:
        "Works with your current system, CSV files, internal archives and shared folders.",
      orLabel: "→",
      nativeLabel: "Collector side",
      nativeTitle: "Activate every artwork",
      nativeBody:
        "Distribute through Gmail, WhatsApp, private links and PDFs, without adding a new platform for the team to learn.",
      note:
        "Designed to sit between the archive and collector conversations. The gallery keeps its current workflow; Vitreen makes it easier to activate artworks, conversations and inquiries.",
      features: [
        {
          label: "01",
          title: "Artwork Sync",
          copy: "Pull selected works from the gallery’s existing database, CSV, or manual upload.",
          image: "/gallery hero mock/artwork-02.png",
        },
        {
          label: "02",
          title: "Private Materials",
          copy: "Generate polished PDFs, private links, or viewing rooms from the selected works.",
          image: "/viewing-room-share.png",
        },
        {
          label: "03",
          title: "Collector Sharing",
          copy: "Send works through email, WhatsApp, or a private link without changing the gallery’s workflow.",
          image: "/gallery hero mock/shoes-exhibition.png",
        },
        {
          label: "04",
          title: "Inquiry Capture",
          copy: "Let collectors reply, ask for details, or inquire directly from the shared material.",
          image: "/artworks/painting-06.png",
        },
        {
          label: "05",
          title: "Sales Routing",
          copy: "Route collector signals back to the right person in the gallery team.",
          image: "/gallery hero mock/frieze-newyork-booth.png",
        },
      ],
    },
    audiences: {
      tabs: ["Galleries", "Artists", "Art Advisors", "Private Collection"],
      soon: "Soon",
      items: [
        {
          title: "A showcase worthy of your programme.",
          description:
            "Present your artists, archive your exhibitions, manage your online catalogue — no technical skills required.",
          features: [
            "Artwork catalogue",
            "Artist pages",
            "Exhibition archive",
            "Contact form",
          ],
        },
        {
          title: "Your work deserves its own space.",
          description:
            "A portfolio built for you — biography, exhibition CV, work series — updated by you, without any intermediary.",
          features: [
            "Online portfolio",
            "Series & works",
            "Exhibition CV",
            "Direct contact",
          ],
        },
        {
          title: "Share selections, not files.",
          description:
            "Present your recommendations to clients in a professional, confidential and easy-to-navigate space.",
          features: [
            "Selection sharing",
            "Client spaces",
            "Detailed artwork sheets",
            "Confidential interface",
          ],
        },
        {
          title: "Your collection, organised and accessible.",
          description:
            "Centralise all your works in a private space — records, documents, history — everything in one place.",
          features: [
            "Full inventory",
            "Detailed records",
            "Associated documents",
            "Secure access",
          ],
        },
      ],
    },
    showcase: {
      title: "And behind the scenes, a workspace connected to galleries.",
      subtitle:
        "Inquiries, exhibitions, artworks. The tools needed to publish, share and follow up.",
      cards: [
        {
          title: "Inquiries linked to artworks.",
          desc: "Every inquiry arrives with useful context: artist, artwork, private selection or viewing room.",
        },
        {
          title: "Prepare exhibitions once.",
          desc: "Selected artworks feed pages, viewing rooms and collector presentations.",
        },
        {
          title: "Artwork data ready to move.",
          desc: "Price, status, medium and artist information stay available for collector-facing surfaces.",
        },
      ],
      bio: [
        "Sacha Elron (born 1960 in Oklahoma City, Oklahoma) is an American painter celebrated for his large-scale meditative landscapes. Trained in figurative painting at the Art Students League of New York, he quickly developed a distinctive visual language oscillating between representation and pure abstraction.",
        "His work is rooted in the contemplation of nature — vast skies, luminous horizons, solitary trees — which he distils into saturated, dense and silent colour fields. Working primarily in oil on canvas, Sacha Elron builds his paintings through successive layers of pigment, occasionally allowing underlying strata to show through as traces of time.",
        "His solo exhibitions have been held at major galleries in New York, Los Angeles, Paris and Berlin. His works are held in numerous public and private collections, including the Whitney Museum of American Art, the Mus\u00e9e d\u2019Art Moderne de Paris, and several European foundations dedicated to contemporary painting.",
        "In 2008, he received the Pollock-Krasner Foundation Award, one of the most prestigious honours in the American art world. In 2015, a retrospective was dedicated to him at the Fondation Beyeler in Basel, bringing together more than 80 works spanning thirty years of practice.",
        "Sacha Elron lives and works in Brooklyn, New York, in a studio he has occupied since 1994.",
      ],
      readBio: "Read full biography",
    },
    solution: {
      title: "Every artwork. Everywhere it matters.",
      subtitle:
        "Update your website, private selections and collector inquiries from one place.",
      cards: [
        {
          title: "Artwork inquiry",
          desc: "Each artwork starts a private conversation with the gallery, without a cart or online checkout.",
        },
        {
          title: "Private Sharing",
          desc: "Send a viewing room as a polished email, with an Inquire button on every work.",
        },
        {
          title: "Collector Selections",
          desc: "Add works to a selection right from the conversation and share it as a ready-made PDF.",
        },
      ],
      mock: {
        artworkManagement: "Artwork Management",
        medium: "Oil on canvas",
        inquire: "Inquire",
        onRequest: "On request",
        synced: "Synced",
        importing: "IMPORT",
      },
    },
    homeAddIns: {
      title: "Reply, share, send.",
      subtitle: "Use the same artwork information across Gmail, WhatsApp and PDF.",
      cards: {
        gmail: {
          title: "Gmail",
          description:
            "Find an artwork and insert its information directly into an email.",
        },
        whatsapp: {
          title: "WhatsApp",
          description:
            "Turn an artwork selection into a clean PDF, ready to send.",
        },
        excel: {
          title: "Excel",
          description:
            "Sync existing inventory sheets with structured artwork records.",
        },
      },
    },
    signatureDemo: {
      title: "One artwork, shared across every gallery surface.",
      subtitle:
        "Change its price once and the website, PDF and viewing room update with it.",
      sourceLabel: "Gallery OS",
      priceLabel: "Price",
      statusLabel: "Availability",
      available: "Available",
      saved: "Saved",
      outputs: [
        { label: "Website", status: "Up to date" },
        { label: "PDF", status: "Up to date" },
        { label: "Viewing Room", status: "Up to date" },
      ],
    },
    processFlow: {
      title: "Starting from your existing gallery",
      subtitle: "We adapt Vitreen to the way your team works.",
      steps: [
        {
          number: "01",
          title: "Start from your existing setup",
          desc: "Connect your current system, CSV files or spreadsheets, or manage artworks directly inside the Vitreen Artwork Library.",
          week: "CONNECT",
        },
        {
          number: "02",
          title: "Prepare artworks for publishing",
          desc: "Artwork data is structured for exhibitions, viewing rooms, private selections, PDFs and website publishing.",
          week: "STRUCTURE",
        },
        {
          number: "03",
          title: "Share and follow up continuously",
          desc: "Publish, send and track collector-facing outputs from the same artwork source.",
          week: "OPERATE",
        },
      ],
    },
    stepper: {
      title: "Publishing content, effortlessly",
      subtitle:
        "You publish independently. Add your works and they appear instantly on your website.",
      steps: [
        {
          title: "Add an artwork",
          desc: "Simple form, published in one click.",
        },
        {
          title: "Site updated",
          desc: "The artwork appears instantly, no code required.",
        },
        {
          title: "Share",
          desc: "Link, private Viewing Room, collector email.",
        },
      ],
      mock: {
        admin: {
          workspace: "My gallery space",
          online: "Online",
          sidebar: ["Works", "Artists", "Exhibitions", "Viewing Rooms"],
          newArtwork: "New artwork",
          publish: "Publish",
          titleField: "Title",
          artistField: "Artist",
          imageField: "Image",
          dragClick: "Drag or click",
          priceField: "Price",
          priceValue: "On request",
          dimField: "Dimensions",
        },
        livesite: {
          navItems: ["Works", "Artists", "Exhibitions", "Contact"],
          technique: "Medium",
          techniqueValue: "Oil on canvas",
          dimensions: "Dimensions",
          price: "Price",
          priceValue: "On request",
          inquire: "Price on request",
          liveStatus: "Live \u2014 updated 2 seconds ago",
        },
        share: {
          newMessage: "New message",
          notifyCollector: "Notify a collector",
          from: "From",
          to: "To",
          subject: "Subject",
          artworkSub: "Claire Fontaine \u00b7 On request",
          send: "Send",
          sent: "Sent",
          recipientsCount: "1 of 3 collectors",
        },
      },
    },
    services: {
      title: "What you receive",
      subtitle: "A connected Gallery OS, built around the way you already work.",
      cards: {
        website: {
          label: "Connected website",
          title: "Website",
        },
        dashboard: { label: "Artworks", title: "Database" },
        pdf: { label: "Collector material", title: "Private Selection editor" },
        addins: { label: "Add-ins", title: "Add-ins" },
        gmail: { label: "Gmail", title: "Your artworks inside email." },
        whatsapp: { label: "WhatsApp", title: "Selections ready to send." },
      },
      items: [
        {
          tier: "gallery-os",
          name: "Your connected Gallery OS",
          description:
            "A connected website, an artwork dashboard and the tools to prepare collector conversations.",
          featuresHeading: "INCLUDED",
          features: [
            "Gallery workflow audit",
            "Website connected to artwork records",
            "Artwork dashboard",
            "Gmail and WhatsApp add-ins",
            "Simple PDF export",
            "Private collector selections",
          ],
          delivery: undefined as string | undefined,
          cta: "Talk to us",
          highlight: false as const,
        },
      ],
    },
    pricingBand: {
      title: "A clear price.",
      subtitle: "One offer, everything included.",
      pilotPill: "Pilot programme — 3 places · setup at −50%",
      base: {
        title: "Gallery OS",
        description: "Your complete system, built around your gallery.",
        price: "€5,000",
        priceDetail: "One-time setup, including implementation and the first year of support.",
        features: [
          "Dashboard for artworks, artists and exhibitions",
          "Website connected to your artwork records",
          "Gmail and WhatsApp add-ins",
          "PDF exports and private selections",
          "Data migration included",
          "Hosting, updates and support for 12 months",
        ],
        note: "Delivered in ~3 weeks",
        cta: "Talk to us",
      },
      partner: {
        title: "Partner option",
        description: "For galleries that would rather delegate the day-to-day.",
        price: "+€350/month",
        priceDetail: "Ongoing support to operate and improve your Gallery OS.",
        features: [
          "Website and content updates done for you",
          "Collector PDFs and private selections prepared for you",
          "New pages and small interface improvements",
          "Monthly working session to review and improve the system",
          "Priority support between sessions",
        ],
      },
      pricingLink: "See details →",
    },
    pricing: {
      hero: {
        title: "Clear costs, no surprise.",
        subtitle: "A fixed setup price and a monthly subscription.",
      },
      offer: {
        eyebrow: "One offer",
        title: "Gallery OS",
        description: "Your complete system, built around your gallery.",
        price: "€5,000",
        priceDetail: "one-time setup",
        features: [
          "Dashboard for artworks, artists and exhibitions",
          "Website connected to your artwork records",
          "Gmail and WhatsApp add-ins",
          "PDF exports and private selections",
          "Data migration included",
          "Hosting, updates and support",
        ],
        deliveryNote: "Delivered in ~3 weeks",
        note:
          "The exact scope is defined during a first conversation — that scope determines the final quote.",
      },
      partnerOption: {
        eyebrow: "Option",
        title: "Partner",
        description: "For galleries that would rather delegate the day-to-day.",
        price: "+€350/month",
        qualifier: "on top of your Gallery OS",
        cta: "Add Partner",
        features: [
          "A monthly call with your dedicated contact",
          "Content updates done for you",
          "Collector material prepared for you",
          "New pages and sections on request",
          "Priority support",
        ],
      },
      pilot: {
        eyebrow: "Pilot programme",
        title: "Three pilot galleries",
        body:
          "The first three galleries receive pilot setup pricing in exchange for a published case study.",
        referencePrice: "€5,000",
        discount: "−50%",
        price: "€2,500",
        availability: "3 places — first come, first served.",
        cta: "Talk to us",
      },
      costAnchor: {
        title: "What Vitreen replaces",
        items: [
          {
            title: "Inventory tool",
            cost: "Around €200–300/month",
            description: "To store and maintain artwork records.",
          },
          {
            title: "Website agency or provider",
            cost: "Around €4,000–8,000 + fees for each change",
            description: "To build the website, then intervene whenever content changes.",
          },
          {
            title: "Team data entry",
            cost: "Several hours every week",
            description:
              "To copy the same information into the website, PDFs and collector emails.",
          },
        ],
        conclusion: "One system, one point of contact.",
      },
      faq: {
        title: "Questions about the offer",
        items: [
          {
            q: "Who owns my data?",
            a: "You do. A complete export is available at any time.",
          },
          {
            q: "Why a 12-month engagement?",
            a: "Monthly support is what keeps the system alive; setup alone is not enough.",
          },
          {
            q: "What happens if I stop?",
            a: "You leave with your data and content.",
          },
          {
            q: "How long does setup take?",
            a: "Around three weeks, from the first conversation to launch.",
          },
          {
            q: "Who handles daily updates?",
            a: "You do, independently. And if you would rather delegate, the Partner option handles it for you.",
          },
        ],
      },
      cta: "Talk to us",
    },
    statementSplit: {
      statTitle: "Online art is redefining the economics of the art market",
      stats: [
        {
          value: "$10.5B",
          label: "Online sales in 2024",
          sub: "Global market",
        },
        { value: "18%", label: "Of the total market", sub: "Digital share" },
        { value: "+76%", label: "Vs pre-pandemic", sub: "Since 2019" },
        {
          value: "40.5M",
          label: "Transactions in 2024",
          sub: "+3% year-on-year",
        },
      ],
      amplifyTitle: "Amplify your gallery\u2019s influence",
      blocks: [
        {
          heading: "Establish your online presence.",
          body1:
            "Without a credible purchasing channel, you remain invisible to collectors who are already making decisions online \u2014 from anywhere in the world.",
          body2:
            "Vitreen deploys native distribution, enabling you to exhibit, share and make your works continuously accessible, independent of traditional circuits.",
        },
        {
          heading: "Turn curiosity into collecting.",
          body1:
            "Journeys designed to move interest into purchase: less friction, clearer choices, actions that count.",
          body2:
            "Every interaction supports a gradual shift from discovery to engagement, and from attention to a sustained relationship with the work.",
        },
        {
          heading: "Take back control of your relationships.",
          body1:
            "Data, exchanges and history with each collector brought together in one place \u2014 no more information scattered across emails and tools.",
          body2:
            "Vitreen connects artworks, selections and inquiries so every exchange is clearer and easier to follow.",
        },
      ],
    },
    quoteSection: {
      quote:
        "The digital space is a natural extension of the gallery\u2019s storefront. In the current era, a robust online program and dedicated strategy is essential in the art world.",
      name: "Elena Soboleva",
      role: "Global Head of Audience Growth & Intelligence, Art Basel",
    },
    faq: {
      title: "Frequently asked questions",
      items: [
        {
          q: "Can I edit the website myself?",
          a: "Yes, through a simple interface. No technical skills required \u2014 you manage your content independently.",
        },
        {
          q: "How long does it take to go live?",
          a: "Around 3 weeks, from the first conversation to launch.",
        },
        {
          q: "Do I need to use specific software?",
          a: "No. Vitreen can connect to an existing inventory or use the Vitreen Artwork Library as your artwork source.",
        },
        {
          q: "What happens if I want to stop?",
          a: "The partnership runs for 12 months and includes hosting, updates and monthly support.",
        },
        {
          q: "Does Vitreen handle the content?",
          a: "Yes. Monthly support can include catalogue publishing, news preparation and email structuring while you retain control over your content.",
        },
        {
          q: "Will my website be visible on Google?",
          a: "Yes. Every website is SEO-optimised from the start: semantic structure, meta tags, optimised images and indexing tailored to the art market.",
        },
      ],
    },
    tools: {
      sectionLabel: "Tools",
      backToHome: "Back to home",
      featuresLabel: "Included",
      overview: {
        eyebrow: "Tools · Overview",
        title: "A connected view of Vitreen tools.",
        subtitle: "Connected tools for exhibitions, publishing and collector communication.",
        body:
          "Vitreen brings together the tools a gallery needs to publish artworks, prepare private presentations, share selections and follow inquiries — without changing how the team already works.",
        features: [
          "A single artwork source",
          "Web pages, PDFs and viewing rooms",
          "Private sharing for collectors",
          "Inquiry tracking per artwork",
        ],
        cta: "Talk to us",
      },
      archive: {
        eyebrow: "Tools · Artworks Management",
        title: "Artworks Management",
        subtitle: "Artworks, artists and exhibitions organized around your workflow.",
        body:
          "Archive provides a structured base for the gallery's artworks: artists, exhibitions, mediums, dimensions, status. The data stays available for public pages, viewing rooms and collector materials.",
        features: [
          "Artwork, artist and exhibition records",
          "Status, prices and availability",
          "Mediums, dimensions and provenance",
          "Connects to an existing inventory",
        ],
        cta: "Talk to us",
      },
      "viewing-rooms": {
        eyebrow: "Tools · Viewing Rooms",
        title: "Private presentations for collectors.",
        subtitle: "Private presentations for collectors and exhibitions.",
        body:
          "Prepare a selection of artworks in a private space: exhibition context, detailed records and a shareable link. Viewing rooms open by invitation, in a readable and confidential interface.",
        features: [
          "Private selection per collector",
          "Exhibition context and artwork records",
          "Time-limited and access-limited links",
          "Direct inquiry from each artwork",
        ],
        cta: "Talk to us",
        badge: "Soon",
      },
      previews: {
        eyebrow: "Tools · Previews",
        title: "Private artwork presentations.",
        subtitle: "Private artwork presentations for collectors.",
        body:
          "Quickly assemble a preview of artworks to send ahead of a fair, an exhibition or a meeting. A calm layout, shared by private link, email or WhatsApp.",
        features: [
          "Fast artwork selection",
          "Refined artwork records",
          "Sharing by link, email or WhatsApp",
          "PDF export ready to send",
        ],
        cta: "Talk to us",
      },
      publishing: {
        eyebrow: "Tools · Publishing",
        title: "Publish from a single source.",
        subtitle: "Website pages, PDFs and collector communication from the same artwork structure.",
        body:
          "Publishing turns artwork data into public pages, exhibition archives, PDFs and emails sent to collectors — without entering the information twice.",
        features: [
          "Artwork, artist and exhibition pages",
          "Exhibition archives",
          "PDF exports and printable presentations",
          "Collector emails built from artworks",
        ],
        cta: "Talk to us",
      },
      inquiries: {
        eyebrow: "Tools · Inquiries",
        title: "Track collector interest.",
        subtitle: "Track collector interest across artworks and private sharing.",
        body:
          "Inquiries attaches each request to an artwork, a viewing room or a private selection. The gallery keeps the context needed to respond: who, on what, from which share.",
        features: [
          "Inquiries linked to artworks",
          "Viewing room or selection context",
          "Status, follow-up and internal notes",
          "Works with existing client tools",
        ],
        cta: "Talk to us",
      },
      mobile: {
        eyebrow: "Tools · Mobile",
        title: "The gallery publishes from its phone.",
        subtitle: "Gallery publishing, on the go.",
        body:
          "Mobile lets the gallery publish an artwork, update a record or prepare a private share from a phone — on a booth, in transit or during a hang.",
        features: [
          "Add an artwork from the phone",
          "Quick record updates",
          "Private sharing in a few taps",
          "Inquiry follow-up on the move",
        ],
        cta: "Talk to us",
      },
      "custom-operations": {
        eyebrow: "Tools · Custom Operations",
        title: "Adapt Vitreen to the gallery's workflow.",
        subtitle: "Tailored workflows adapted to your gallery.",
        body:
          "Custom Operations adjusts Vitreen to a gallery's specific operations: dedicated fields, integrations with existing tools, internal automations or sharing templates tied to the programme.",
        features: [
          "Custom fields and statuses",
          "Integrations with existing tools",
          "Internal automations",
          "Sharing templates tied to the gallery",
        ],
        cta: "Talk to us",
      },
    },
    solutions: {
      sectionLabel: "Solutions",
      backToHome: "Back to home",
      featuresLabel: "Included",
      relatedLabel: "By role",
      mockCaption: "Preview",
      galleries: {
        eyebrow: "Galleries",
        title: "A connected operating system and website for contemporary galleries.",
        subtitle:
          "A custom Gallery OS and website built around your artworks, exhibitions and collector relationships.",
        body:
          "Vitreen connects the gallery’s existing archives, inventories or databases, then turns artworks into collector-ready material to share — viewing rooms, private selections, PDFs — without replacing your tools.",
        features: [
          "Connect existing archives, inventories or databases",
          "Turn artworks into viewing rooms, PDFs and private links",
          "Keep inquiries connected to the right works",
          "Move smoothly between public publishing and private sharing",
        ],
        cta: "Talk to us",
      },
      advisors: {
        eyebrow: "Advisors & dealers",
        title: "Present the right works to every client.",
        subtitle: "Create artwork selections for each client and share them by link or PDF.",
        body: "",
        features: [
          "Compose a private selection per client",
          "Share by private link, PDF or WhatsApp",
          "Keep follow-up tied to each artwork",
          "Present works without revealing your sources",
        ],
        cta: "Talk to us",
      },
      artists: {
        eyebrow: "Artists",
        title: "Artist website and artwork inventory in one place.",
        subtitle: "Organise your work, update your website and share private presentations.",
        body:
          "For artists and studios, structure the body of work — series, mediums, years, provenance — and present a selection to galleries, curators or collectors through private links.",
        features: [
          "Keep your work organised",
          "Make your website reflect your current practice",
          "Prepare work for each gallery or curator",
          "Your studio assistant",
        ],
        cta: "Talk to us",
      },
      collectors: {
        eyebrow: "Solutions · Collectors",
        title: "Your collection, documented and at hand.",
        subtitle: "Acquisitions and documents in one place, viewing rooms received from galleries.",
        body:
          "For collectors, keep acquisitions, documents and condition information in one place, and receive private viewing rooms from the galleries you work with.",
        features: [
          "Keep acquisitions and documents in one place",
          "Store invoices, certificates and condition reports",
          "Receive private viewing rooms from galleries",
          "Review proposed works before acquiring",
        ],
        cta: "Talk to us",
      },
      estates: {
        eyebrow: "Artist Estates",
        title: "Stewardship of a complete body of work.",
        subtitle: "Corpus, provenance and transmission, under your control.",
        body:
          "For artist estates and foundations, structure the full corpus, preserve provenance and exhibition history, and control how works are presented to institutions and collectors.",
        features: [
          "Structure the complete corpus",
          "Preserve provenance and exhibition history",
          "Control how works are presented",
          "Prepare loans, sales and institutional requests",
        ],
        cta: "Talk to us",
      },
    },
    ctaBand: {
      title: "Give your gallery a new dimension",
      subtitle: "Let’s talk about your project — no commitment",
      cta: "Talk to Vitreen",
    },
    about: {
      eyebrow: "About Vitreen",
      title: "Build the gallery you want to run",
      lead: "Better systems for your artists, collectors and daily work.",
      letter: {
        title: "The next generation of galleries will be built differently.",
        paragraphs: [
          "Galleries have always been built on artists, judgment and relationships.",
          "That should not change.",
          "But the work required to sustain a gallery has changed considerably. Even a small team is now expected to maintain accurate artwork records, keep a website current, prepare private material, respond across multiple channels and follow every collector conversation carefully.",
          "The visible work remains cultural and relational. Behind it, the operational burden keeps growing.",
          "Most galleries respond by adding more tools, more manual processes or more external providers. Information becomes scattered across folders, spreadsheets, emails, PDFs and website systems. Each new request creates another task. Each update depends on someone knowing where the right information is stored.",
          "Vitreen was created around a different idea.",
          "A gallery should be able to operate professionally without becoming larger, heavier or more technical.",
          "Artwork information should be entered once, structured properly and reused wherever the gallery works: on the website, in private selections, in emails, in PDFs and throughout collector conversations.",
          "Technology should not replace the gallery’s judgment or relationships. It should support them.",
          "A stronger operational system allows a gallery to respond faster, follow up more consistently and spend less time rebuilding the same material. It gives the team more capacity for artists, exhibitions and collectors.",
          "For established galleries, this means more control and less dependency.",
          "For younger gallerists, it means being able to start with professional infrastructure before having the resources to build a large team.",
          "We believe the galleries that remain competitive will not be those using the most technology.",
          "They will be those using it with the most clarity — to preserve their knowledge, strengthen their relationships and make better use of every opportunity.",
          "Vitreen is being built for them.",
        ],
        signature: { name: "Rapha\u00ebl Rossi", role: "Founder, Vitreen" },
      },
      audiences: [
        {
          title: "For established galleries",
          text: "Vitreen strengthens existing operations.",
        },
        {
          title: "For new gallerists",
          text: "It provides the infrastructure to start professionally without building a large team from day one.",
        },
      ],
      cta: "Talk to us",
    },
    footer: {
      tagline: "Connected websites and sales tools for art galleries, artists and advisors.",
      columns: {
        platform: "Platform",
        solutions: "Solutions",
        company: "Vitreen",
      },
      links: {
        galleryOs: "Gallery OS",
        artworkManagement: "Artwork Management",
        galleryWebsites: "Gallery Websites",
        viewingRooms: "Private Viewing Rooms",
        galleryAssistant: "Gallery Assistant",
        forGalleries: "For Art Galleries",
        forArtists: "For Artists",
        forAdvisors: "For Art Advisors & Dealers",
        about: "About",
        pricing: "Pricing",
        contact: "Contact",
      },
      location: "Paris, France",
    },
  },
} as const;
